### PR TITLE
Remove null checks and allow it to be queried

### LINKED ISSUE #607: Unexpected scoping behavior
My [reproduction repo](https://github.com/grantholle/bouncer-scoping-reproduction).

The issue is essentially if I add a permission with a scope, then remove the scope entirely and check the same permission, it comes back as a successful check because of missing scoping query clauses when the scope is `null`.

As you can see in my [test](https://github.com/grantholle/bouncer-scoping-reproduction/blob/main/tests/Feature/PermissionAssignmentTest.php), I am removing the scope entirely and checking to see if a user has permission on the current scope (none/`null`). The query without a scope does not explicitly check if `scope = null`, and therefore if a scope is currently not set in the application, the permission will pass regardless of what the original permission's scope was.

In my mind how it should work is that, if a permission is added when there is no scope set, then it should pass regardless of what the set scope is, which is the current behavior (`"permissions"."scope" = # or "permissions"."scope" is null`).

However, if I set a permission with a scope, it *should only work if that is the current scope*. I'm proposing we explicitly set the scope where clauses when there isn't a scope set for the application (`"permissions"."scope" is null`).

### PR DESCRIPTION
**Pull request by grantholle**
Fix #607. This has the expected behavior and not so eager to grant permissions when you may not want them to be granted.

### CODE REVIEW

**Comment by grantholle** [comment]
Also, if you don't mind adding the `hacktoberfest-accepted` tag to this, it would be really helpful in my goal of contributing during Hacktoberfest. Thanks!

**Comment by grantholle** [comment]
I've ran into the same situation when checking roles assignment. I have a scoped assigned role, but when I check `$user->isA($role)` when there isn't a scope set, it still passes.

I will try to include an update for that.

**Comment by grantholle** [comment]
Hi @JosephSilber, any plans to get this merged? Thanks for taking the time!

File: src/Database/Scope/Scope.php [hunk 1]
```diff
@@ -165,10 +161,12 @@ public function applyToRelation(BelongsToMany $relation)
...
-        return $query->where(function ($query) use ($table) {
-            $query->where("{$table}.scope", $this->scope)
-                  ->orWhereNull("{$table}.scope");
-        });
+        return is_null($this->scope)
+            ? $query->whereNull("{$table}.scope")
+            : $query->where(function ($query) use ($table) {
+                    $query->where("{$table}.scope", $this->scope)
+                          ->orWhereNull("{$table}.scope");
+                });
```
Comment (JosephSilber) [inline src/Database/Scope/Scope.php:169]:
```suggestion
        return $query->where(function ($query) use ($table) {
            $query->whereNull("{$table}.scope");

            if (! is_null($this->scope)) {
                $query->orWhere("{$table}.scope", $this->scope)            
            }      
        });
```

File: src/Database/Scope/Scope.php [hunk 2]
```diff
@@ -93,7 +93,7 @@ public function appendToCacheKey($key)
      */
     public function applyToModel(Model $model)
     {
-        if (! $this->onlyScopeRelations && ! is_null($this->scope)) {
+        if (! $this->onlyScopeRelations) {
             $model->scope = $this->scope;
         }
```
Comment (JosephSilber) [inline src/Database/Scope/Scope.php:98]: Why did you have to remove this?

It might be unnecessary. Just curious whether you had to remove it to make this work.

**Comment by JosephSilber** [comment]
Whoops. I should've gotten to this way sooner, especially since you put in all that work creating the issue, the repro repo and a PR with tests! Sorry.

I left you a small review. Check it out, and let's get this merged.

File: src/Database/Scope/Scope.php (hunk 2 above)
Comment (grantholle) [reply src/Database/Scope/Scope.php]: No, keeping still works as expected. I added it back in.

**Comment by grantholle** [comment]
Thanks man, I've made those suggested edits. No worries on the delay!

**Comment by grantholle** [comment]
Never mind, my local repo was out of date with this. Anyway, you were right on all of the suggestions.

**Comment by JosephSilber** [comment]
Merged. Thanks!
